# Dependabot configuration file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "weekly"
      time: "05:03"
  
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
      time: "05:03"
