# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# More information: https://www.neuralegion.com/

name: NeuraLegion

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '39 2 * * 6'

jobs:
  neuralegion_scan:
    runs-on: ubuntu-latest
    name: NeuraLegion Security Scan
    # Only run if the secret is configured
    if: ${{ secrets.NEURALEGION_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v6
      
      - name: Start Nexploit Scan
        id: start
        uses: NeuraLegion/run-scan@29ebd17b4fd6292ce7a238a59401668953b37fbe
        with:
          api_token: ${{ secrets.NEURALEGION_TOKEN }}
          name: GitHub scan ${{ github.sha }}
          discovery_types: |
            [ "crawler" ]
          crawler_urls: |
            [ "https://brokencrystals.com" ]
        continue-on-error: true
